//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Otomaston.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cariler()
        {
            this.Siparislers = new HashSet<Siparisler>();
        }
    
        public int CariId { get; set; }
        public string CariKod { get; set; }
        public string CariAdi { get; set; }
        public string YetkiliAdi { get; set; }
        public string YetkiliSoyadi { get; set; }
        public string CariTelNo { get; set; }
        public string CariTelNo2 { get; set; }
        public string CariAdres { get; set; }
        public string CariVKN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparislers { get; set; }
    }
}
