//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Otomaston
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlisFaturalari
    {
        public int AFaturaId { get; set; }
        public Nullable<int> Cari_id { get; set; }
        public Nullable<System.DateTime> AlısTarihi { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<int> Adet { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> iskonto { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> Stok_id { get; set; }
        public Nullable<int> Personel_id { get; set; }
    
        public virtual Cariler Cariler { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Stoklar Stoklar { get; set; }
    }
}
