//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Otomaston
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirsOtomasyonEntities : DbContext
    {
        public FirsOtomasyonEntities()
            : base("name=FirsOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departman> Departmen { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<StokKategori> StokKategoris { get; set; }
        public virtual DbSet<Stoklar> Stoklars { get; set; }
        public virtual DbSet<Cariler> Carilers { get; set; }
        public virtual DbSet<Siparisler> Siparislers { get; set; }
        public virtual DbSet<SiparisDurum> SiparisDurums { get; set; }
        public virtual DbSet<AlisFaturalari> AlisFaturalaris { get; set; }
        public virtual DbSet<AktifPasifDurum> AktifPasifDurums { get; set; }
    }
}
