//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Otomaston
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Siparislers = new HashSet<Siparisler>();
            this.AlisFaturalaris = new HashSet<AlisFaturalari>();
        }
    
        public int Personelid { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string DogumTarihi { get; set; }
        public string DogumYeri { get; set; }
        public string TcNo { get; set; }
        public string TelefonNo { get; set; }
        public string KullaniciAdi { get; set; }
        public string Password { get; set; }
        public Nullable<int> Departman_id { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Durum_id { get; set; }
    
        public virtual Departman Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparislers { get; set; }
        public virtual AktifPasifDurum AktifPasifDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlisFaturalari> AlisFaturalaris { get; set; }
    }
}
